[package]
name = "udp_traffic_generator"
version = "0.1.1"
edition = "2021"
authors = ["Flavio Bizzarri <fl.bizzarri@gmail.com>"]
license = "Apache-2.0"
description = "A tool to generate UDP traffic"
readme = "README.md"
homepage = "https://github.com/newfla/Rust-UDP-Traffic-Generator"
repository = "https://github.com/newfla/Rust-UDP-Traffic-Generator"
keywords = ["cli", "udp", "client", "traffic", "generator"]
categories = ["command-line-utilities"]

[dependencies]
log = "0.4"
simple_logger = "2.2.0"
rand = "0.8"
clap = "3.2.14"
byte-unit = "4.0.14"
tokio = { version = "1.20.0", features = ["full"] }
